### ISSUE TITLE
Clean up Timer class

### ISSUE THREAD

**Issue by samhocevar** [lolengine/lolengine#4]
Find something from C++11 that we can use to replace all the code in `src/sys/timer.cpp`, then put it in `src/lol/sys/timer.h`, then get rid of `src/sys/timer.cpp`. While at it, rename `lol::Timer` to `lol::timer` and everyting else to lowercase.

**Comment by gbittoun** [comment]
Done => https://github.com/lolengine/lol/commit/6dcc4a5275409537de1369c7d49dc15528b5e02e
