### ISSUE TITLE
missing glext.h include without glew

### ISSUE THREAD

**Issue by notwa** [lolengine/lolengine#8]
I'm building lolengine (well, specifically lolremez) on [msys2](http://www.msys2.org/) for the heck of it. it built successfully after making this change, though I haven't actually tested OpenGL support. installing glew also works, as you'd expect.

```diff
diff --git a/src/lolgl.h b/src/lolgl.h
index 373ea2ae..ac301f84 100644
--- a/src/lolgl.h
+++ b/src/lolgl.h
@@ -47,4 +47,5 @@
 #       define GL_GLEXT_PROTOTYPES
 #       include <GL/gl.h>
+#       include <GL/glext.h>
 #   endif
 #elif defined HAVE_GLES_2X
```

otherwise, I get a ton of missing enumerations, declarations, etc. when attempting to compile files like `src/gpu/shader.cpp`.

**Comment by samhocevar** [comment]
This makes sense, thanks! I’m an MSYS2 user myself.
